run:
  go: "1.20"
  concurrency: 4
  timeout: 10s
  skip-dirs:
    - tmp/
  skip-dirs-use-default: true
  skip-files:
    - ".*generated.*"
    - ".*\\.pb\\.go$"
  allow-parallel-runners: true
  tests: false

linter-settings:
  govet:
    check-shadowing: true
  godox:
    keywords:
      - NOTE
      - TODO
      - FIXME
      - BUG
      - DEPRECATED
      - Deprecated

linters:
  enable-all: true
  disable:
    - interfacer
    - scopelint
    - golint
    - maligned
    - wsl
    - nlreturn
    - gomnd
    - gofumpt
    - ireturn
    - exhaustivestruct
    - nosnakecase
    - varcheck
    - deadcode
    - ifshort
    - structcheck
    - wastedassign
    - rowserrcheck
