version: "2"

linters:
  settings:
    godox:
      keywords:
        - NOTE
        - TODO
        - FIXME
        - BUG
        - DEPRECATED
        - Deprecated
  exclusions:
    paths:
      - ".*generated.*"
      - ".*\\.pb\\.go$"
      - ".*/tmp/.*"

issues:
  max-issues-per-linter: 10

run:
  concurrency: 4
  timeout: 30s
  allow-parallel-runners: true
  tests: false
