uri: https://github.com/berquerant/mpv-settings
branch: main
locald: repos/mpv-settings
lock: locks/mpv-settings.lock
env:
  MUSIC_ROOT: "${MUSIC_ROOT}"
  YTDL_ROOT: "${HOME}/ytdl"
check:
  - |
    if [ -z "$MUSIC_ROOT" ] ; then
      echo "Please set MUSIC_ROOT" > /dev/stderr
      exit 1
    fi
setup:
  - arch -arm64 brew install mpv
install:
  - ./install.sh
