;;; my-gron.el --- my gron integration -*- lexical-binding: t -*-

;;; Code:

(require 'my-proc)

(defcustom my-gron-command (my-getenv-join "DOTFILES_ROOT" "bin" "gron.sh")
  "gron.sh.")

(defun my-gron-run (ext pattern)
  "Call `my-gron-command' with current buffer."
  (my-proc-call-process my-gron-command
                        nil
                        ext
                        pattern
                        (buffer-file-name))
  (display-buffer (get-buffer-create my-proc-call-process-buffer)))

(defmacro my-gron--defun (ext)
  (let ((fname (intern (format "my-gron-run-%s" ext)))
        (doc (format "Generated by `my-gron--defun'.
Call `my-gron-run' with %s." ext)))
    `(progn
       (defun ,fname (pattern)
         ,doc
         (interactive "sPattern: ")
         (my-gron-run ,ext pattern)))))

(my-gron--defun "json")
(my-gron--defun "yaml")
(my-gron--defun "toml")
(my-gron--defun "xml")

(provide 'my-gron)
;;; my-gron.el ends here
