((bash . ("https://github.com/tree-sitter/tree-sitter-bash" "v0.25.1"))
 ; (c . ("https://github.com/tree-sitter/tree-sitter-c" "v0.24.1"))
 (cpp . ("https://github.com/tree-sitter/tree-sitter-cpp" "v0.23.4"))
 (css . ("https://github.com/tree-sitter/tree-sitter-css" "v0.25.0"))
 (dockerfile . ("https://github.com/camdencheek/tree-sitter-dockerfile" "v0.2.0"))
 (go . ("https://github.com/tree-sitter/tree-sitter-go" "v0.25.0"))
 (javascript . ("https://github.com/tree-sitter/tree-sitter-javascript" "v0.25.0"))
 (json . ("https://github.com/tree-sitter/tree-sitter-json" "v0.24.8"))
 (markdown . ("https://github.com/tree-sitter-grammars/tree-sitter-markdown" "v0.5.2" "tree-sitter-markdown/src"))
 (php . ("https://github.com/tree-sitter/tree-sitter-php" "v0.24.2" "php/src"))
 (python . ("https://github.com/tree-sitter/tree-sitter-python" "v0.25.0"))
 (ruby . ("https://github.com/tree-sitter/tree-sitter-ruby" "v0.23.1"))
 (rust . ("https://github.com/tree-sitter/tree-sitter-rust" "v0.24.0"))
 (scala . ("https://github.com/tree-sitter/tree-sitter-scala" "v0.24.0"))
 ; (sql . ("https://github.com/DerekStride/tree-sitter-sql" "v0.3.11" "src"))
 (toml . ("https://github.com/tree-sitter-grammars/tree-sitter-toml" "v0.7.0"))
 (typescript . ("https://github.com/tree-sitter/tree-sitter-typescript" "v0.23.2" "typescript/src"))
 (tsx . ("https://github.com/tree-sitter/tree-sitter-typescript" "v0.23.2" "tsx/src"))
 (xml . ("https://github.com/tree-sitter-grammars/tree-sitter-xml" "v0.7.0" "xml/src"))
 (yaml . ("https://github.com/tree-sitter-grammars/tree-sitter-yaml" "v0.7.2")))
