services:
  # To enable tools, add http://mcpo:8000/markitdown to tools in admin panel
  mpco:
    build:
      context: mcpo
      dockerfile: Dockerfile
    image: open-webui-mcpo-local
    container_name: mcpo
    restart: unless-stopped
    volumes:
      - "${HOME}/.docker/run/docker.sock:/var/run/docker.sock:ro"
    expose:
      - "8000"
    ports:
      - "${MCPO_PORT-8000}:8000"

  ollama:
    volumes:
      - ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:${OLLAMA_DOCKER_TAG-latest}
    expose:  # for open-webui container
      - "11434"
    ports:
      - "${OLLAMA_PORT-11434}:11434"

  open-webui:
    build:
      context: .
      args:
        OLLAMA_BASE_URL: '/ollama'
      dockerfile: Dockerfile
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - ${OPEN_WEBUI_PORT-3000}:8080
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434'
      - 'WEBUI_SECRET_KEY='
      - 'ENABLE_RAG_WEB_SEARCH=true'
      - 'RAG_WEB_SEARCH_ENGINE=tavily'
      - 'TAVILY_API_KEY=${TAVILY_API_KEY}'
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

volumes:
  ollama: {}
  open-webui: {}
