services:
  # To enable tools, add http://mcpo:8000/markitdown to tools in admin panel
  mcpo:
    build:
      context: mcpo
      dockerfile: Dockerfile
    image: open-webui-mcpo-local
    container_name: mcpo
    restart: unless-stopped
    volumes:
      - "${HOME}/.docker/run/docker.sock:/var/run/docker.sock:ro"
    expose:
      - "8000"
    ports:
      - "${MCPO_PORT-8000}:8000"

  # ollama:
  #   volumes:
  #     - "${OPEN_WEBUI_VOLUMES_ROOT}/ollama:/root/.ollama"
  #   container_name: ollama
  #   pull_policy: always
  #   tty: true
  #   restart: unless-stopped
  #   image: ollama/ollama:${OLLAMA_DOCKER_TAG-latest}
  #   expose:  # for open-webui container
  #     - "11434"
  #   ports:
  #     - "${OLLAMA_PORT-11434}:11434"

  open-webui:
    build:
      context: .
      args:
        OLLAMA_BASE_URL: '/ollama'
      dockerfile: Dockerfile
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    container_name: open-webui
    volumes:
      - "${OPEN_WEBUI_VOLUMES_ROOT}/open-webui:/app/backend/data"
    # depends_on:
    #   - ollama
    ports:
      - ${OPEN_WEBUI_PORT-3000}:8080
    environment:
      # - 'OLLAMA_BASE_URL=http://ollama:11434'
      - 'OLLAMA_BASE_URL=http://host.docker.internal:${OLLAMA_PORT}'
      - 'WEBUI_SECRET_KEY='
      - 'ENABLE_RAG_WEB_SEARCH=true'
      - 'RAG_WEB_SEARCH_ENGINE=tavily'
      - 'TAVILY_API_KEY=${TAVILY_API_KEY}'
      - 'ENABLE_OPENAI_API=true'
      - 'OPENAI_API_KEY=${OPENAI_API_KEY}'
      - 'USE_CUDA_DOCKER=true'
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
